title: React Guidelines
description: Guidelines' document for the React team
theme: just-the-docs

url: https://spaceUY.github.io/react-guidelines

aux_links:
  React native docs: https://spaceUY.github.io/react-native-guidelines
